copyright: Copyright 2021
author: Gianmaria Bajo
title: tasks.vim
email: mg1979.git@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
        A vim plugin
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mg979

# Build settings
# theme: jekyll-theme-yat
remote_theme: "jeffreytse/jekyll-theme-yat"
# theme: minima
# plugins:
        # - jekyll-feed

night_mode: "off"

# Code badge setting
# You can enable or disable the code badge and so on
code_badge:
        enabled: "false"
        color: "#fff"
        background_color: "#ff4e00"
        text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
        - index.md
        - 1-async.md
        - 2-tasks.md
        - 3-examples.md

# paginate: 2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
